"""create_questions_paths_quiz_and_admin_tables

Revision ID: 0bdbb1446b1f
Revises: a0ac26be9ac2
Create Date: 2026-09-07 21:59:55.326133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdbb1446b1f'
down_revision: Union[str, Sequence[str], None] = 'a0ac26be9ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_track'), ['track'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('qtype', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('generator_key', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)

    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_step_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'step_id')
    )
    op.create_table('path_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_slug', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['path_slug'], ['learning_paths.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('path_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_path_steps_path_slug'), ['path_slug'], unique=False)

    op.create_table('question_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_reviews_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_spec', sa.Text(), nullable=False),
    sa.Column('question_ids', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('user_question_exposure',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('shown_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    with op.batch_alter_table('user_question_exposure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_question_exposure_shown_at'), ['shown_at'], unique=False)

    op.create_table('quiz_attempt_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_answers_attempt_id'))

    op.drop_table('quiz_attempt_answers')
    with op.batch_alter_table('user_question_exposure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_question_exposure_shown_at'))

    op.drop_table('user_question_exposure')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_created_at'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_question_reviews_question_id'))

    op.drop_table('question_reviews')
    with op.batch_alter_table('path_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_path_steps_path_slug'))

    op.drop_table('path_steps')
    op.drop_table('path_step_progress')
    op.drop_table('admin_audit_log')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic'))
        batch_op.drop_index(batch_op.f('ix_questions_review_status'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))
        batch_op.drop_index(batch_op.f('ix_questions_content_hash'))

    op.drop_table('questions')
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_track'))

    op.drop_table('learning_paths')
    # ### end Alembic commands ###
