"""create_progress_tables

Revision ID: 3fbedcb45983
Revises: 184cc17df8ca
Create Date: 2026-09-07 21:39:33.239190

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fbedcb45983"
down_revision: str | Sequence[str] | None = "184cc17df8ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_days",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("action_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "day"),
    )
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "item_type", "item_id"),
    )
    op.create_table(
        "notes",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("problem_slug", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "problem_slug"),
    )
    op.create_table(
        "problem_progress",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("problem_slug", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "problem_slug"),
    )
    op.create_table(
        "visualizer_completions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("visualizer_id", sa.String(), nullable=False),
        sa.Column("visits", sa.Integer(), nullable=False),
        sa.Column("first_completed_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "visualizer_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_imported_local", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("has_imported_local")

    op.drop_table("visualizer_completions")
    op.drop_table("problem_progress")
    op.drop_table("notes")
    op.drop_table("bookmarks")
    op.drop_table("activity_days")
    # ### end Alembic commands ###
