"""create_problems_and_submissions_tables

Revision ID: a0ac26be9ac2
Revises: 3fbedcb45983
Create Date: 2026-09-07 21:47:35.669345

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0ac26be9ac2'
down_revision: str | Sequence[str] | None = '3fbedcb45983'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('examples', sa.Text(), nullable=False),
    sa.Column('constraints_json', sa.Text(), nullable=False),
    sa.Column('hints', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_problems_review_status'), ['review_status'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_problems_topic'), ['topic'], unique=False)

    op.create_table('problem_solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('complexity', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('is_reference', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['problems.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem_solutions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_problem_solutions_problem_slug'), ['problem_slug'], unique=False
        )

    op.create_table('problem_test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_slug', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('expected_json', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['problems.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem_test_cases', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_problem_test_cases_problem_slug'), ['problem_slug'], unique=False
        )

    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('problem_slug', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('runtime_ms', sa.Float(), nullable=False),
    sa.Column('test_results', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_submissions_problem_slug'), ['problem_slug'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_problem_slug'))

    op.drop_table('submissions')
    with op.batch_alter_table('problem_test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_test_cases_problem_slug'))

    op.drop_table('problem_test_cases')
    with op.batch_alter_table('problem_solutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_solutions_problem_slug'))

    op.drop_table('problem_solutions')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_topic'))
        batch_op.drop_index(batch_op.f('ix_problems_review_status'))
        batch_op.drop_index(batch_op.f('ix_problems_difficulty'))

    op.drop_table('problems')
    # ### end Alembic commands ###
